### ISSUE TITLE
NagiosQL Plugin Timeout Issue: check_ssh: Timeout value must be a positive integer (not sure if this is the right place to post this)

### ISSUE THREAD

**Issue by DogasNetwork** [LUCKFBO/nagiosql#1]
For some reason I can't seem to find where this error is coming from.

It is being displayed on the Nagios Core Dashboard. 

I've added the check command of "**check_ssh**" at one of the services at the Services section of the NagiosQL.

The argument where the $ARG1$ field was I've added the following formula: **-t '################' -M processes**   

check_ssh: Timeout value must be a positive integer
Usage:
check_ssh [-4 -6] [-t <timeout>] [-r <remote version>] [-p <port>] <host>

![Nagios_Core_Dashboard-check_ssh_timeout_issue](https://user-images.githubusercontent.com/35688835/159646149-4d6915e4-a225-4eec-bf65-c47a6a794013.PNG)

**Comment by LUCKFBO** [comment]
You are passing a non-numeric value as a parameter in -t

Assuming this is the way of the your plugin try to execute a check_ssh on your linux console
usr/lib/nagios/plugins/check_ssh -H www.google.com -t 10 

Also check

Accept arguments

Options:
     -h, --help
        Print detailed help screen
     -V, --version
        Print version information
     --extra-opts=[section][@file]
        Read options from an ini file. See
        https://www.nagios-plugins.org/doc/extra-opts.html
        for usage and examples.
     -H, --hostname=ADDRESS
        Host name, IP Address, or unix socket (must be an absolute path)
     -p, --port=INTEGER
        Port number (default: 22)
     -4, --use-ipv4
        Use IPv4 connection
     -6, --use-ipv6
        Use IPv6 connection
     -t, --timeout=INTEGER:<timeout state>
        Seconds before connection times out (default: 10)
        Optional ":<timeout state>" can be a state integer (0,1,2,3) or a state STRING
     -r, --remote-version=STRING
        Alert if string doesn't match expected server version (ex: OpenSSH_3.9p1)
     -P, --remote-protocol=STRING
        Alert if protocol doesn't match expected protocol version (ex: 2.0)
     -v, --verbose
        Show details for command-line debugging (Nagios may truncate output)

    Send email to help@nagios-plugins.org if you have questions regarding use
    of this software. To submit patches or suggest improvements, send email to
    devel@nagios-plugins.org

Try to check your config file of ssh on a Debian/Ubuntu system are: /etc/nagios-plugins/config/ssh.cfg. Verify if check_ssh contains $ARGS1$ parameter as you want above.
Ps. The path of command line could be different depends where you installed.

define command{
  command_name  check_ssh
  command_line  /usr/lib/nagios/plugins/check_ssh '$HOSTADDRESS$' $ARG1$
}
